#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in metadata.json
#metadata

# use dependencies defined in Modulefile
# modulefile

mod 'stahnma/epel'
mod 'aboe/chrony'
mod 'puppetlabs/mysql'
mod 'puppetlabs/rabbitmq',
    :git => 'https://github.com/puppetlabs/puppetlabs-rabbitmq.git'
mod 'openstack/keystone'
mod 'openstack/glance'
mod 'openstack/nova',
    :git => 'git@github.com:stieizc/puppet-nova.git'
mod 'openstack/neutron',
    :git => 'https://github.com/openstack/puppet-neutron.git'
mod 'openstack/horizon'

# Solve dependency issue between rabbitmq & openstacklib
mod 'puppetlabs/apt', '1.8.0'
mod 'puppetlabs/stdlib'
#mod 'puppetlabs/vcsrepo'

exclusion 'puppetlabs/postgresql'
exclusion 'puppetlabs/apt'

# A module from git
# mod 'puppetlabs-ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# A module from a git branch/tag
# mod 'puppetlabs-apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => '1.4.x'

# A module from Github pre-packaged tarball
# mod 'puppetlabs-apache', '0.6.0', :github_tarball => 'puppetlabs/puppetlabs-apache'
